### ISSUE TITLE
unable to start plugin (no docs)

### ISSUE THREAD

**Issue by simple-git-user** [puppetmaster-/tileset_plugin#22]
thanks for this plugin!
I am using any godot plugin  first time, followed all instructions given but no clue how to see start plugin,where to start seeing what is shown in first snapshot

**Comment by puppetmaster-** [comment]
Have you installed this plugin from Asset Library?
After installing you need to activate it under project settings.

**Comment by ttencate** [comment]
Also new to Godot and running into the same. The plugin is installed; I see it in `res://addons/ch.fischspiele.tilesethelper`. I've set it to Active it in Scene > Project Settings > Plugins. But the Tileset window from the [GIF](https://gifyu.com/images/multicreate.gif) is nowhere to be seen. How to open that?

I also tried Scene > Run Script > `tilesethelper.gd` but I get an error "Couldn't instance script: Did you forget the 'tool' keyword?", so that's probably not the way forward (especially because the script _does_ start with the `tool` keyword).

Edit: I don't know what I did exactly, but something with `tilesethelper_dock.tscn` made the Tileset panel show up in the bottom right, next to Inspector and Node. Yay!

**Comment by puppetmaster-** [comment]
@ttencate Which godot version are you using?

**Comment by ttencate** [comment]
2.1.4 on Arch Linux.

**Comment by puppetmaster-** [comment]
I will close this issue, if there is still a problem it can be reopen.
